task_name: CloseBox
category_name: Articulated

tool_keypoint_name_list: [tool_head, tool_tail, tool_side]
object_keypoint_name_list: [articulated_object_head, articulated_object_tail]

constraint_list:
# ensure the gripper to be in contact with the box lid with whole fingers
- keypoint_name: tool_tail
  target_keypoint_name: articulated_object_head
  tolerance: 0.0001
  type: point2point_constraint

# ensure surface of the gripper to be parallel to the box lid
- axis_from_keypoint_name: tool_head
  axis_to_keypoint_name: tool_side
  target_axis: [1.0, 0, 0]
  target_axis_frame: object
  tolerance: 0.01
  target_inner_product: 1
  type: frame_axis_parallel

# - axis_from_keypoint_name: tool_head
#   axis_to_keypoint_name: tool_tail
#   target_axis_from_keypoint_name: articulated_object_head
#   target_axis_to_keypoint_name: articulated_object_tail
#   tolerance: 0.01
#   target_inner_product: -1
#   type: keypoint_axis_parallel

# # ensure gripper to point directly to the direction of the box
# - axis_from_keypoint_name: tool_head
#   axis_to_keypoint_name: tool_side
#   target_axis_from_keypoint_name: articulated_object_head
#   target_axis_to_keypoint_name: articulated_object_tail
#   tolerance: 0.01
#   target_inner_product: 0
#   type: keypoint_axis_orthogonal

- axis_from_keypoint_name: tool_head
  axis_to_keypoint_name: tool_tail
  target_axis: [1.0, 0, 0]
  target_axis_frame: object
  tolerance: 0.01
  target_inner_product: 0
  type: frame_axis_orthogonal



# for pre-actuation and post-actuation motions. 
# Each motion is represented in the [mode,value] format
# mode: translate or rotate
# value: [x,y,z] in the tool frame for translate or radian for rotate
# Units are in meters and radians respectively.

# pre-actuation pose list. 
pre_actuation_motions: [["translate_x", 0.06], ["translate_z", -0.15]] # [adjust gripper direction and approach, move gripper above lid]

# post-actuation pose list
post_actuation_motions: [["translate_z", 0.08], ["translate_x", -0.3]] # [press lid down]

# trajectory time
actuation_time: 24 # time to reach task goal pose
pre_actuation_times: [16, 20]
post_actuation_times: [26, 32]